### ISSUE TITLE
Add to Meta Data slot

### ISSUE THREAD

**Issue by samuel-marsh** [samuel-marsh/scCustomize#17]
- [ ] Add new column based on values of other columns
- [ ] Add based on cell barcode prefix
- [ ] Add based on specific set of cell barcodes
