### ISSUE TITLE
v0.7.2 Roadmap

### ISSUE THREAD

**Issue by samuel-marsh** [samuel-marsh/scCustomize#39]
0.7.1 planned to release before end of May 2022.

Next release will be either 0.7.2 or 0.8.0 depending on features/changes.

Plans for next release:
- [ ] Cluster DotPlot extra annotation #18 
- [ ] Examine cli/rlang progress bars
- [ ] Examine progressr/furrr progress bars
- [ ] Progress bars on parallel functions
- [ ] More
