### ISSUE TITLE
v1.0.0 Release Prep

### ISSUE THREAD

**Issue by samuel-marsh** [samuel-marsh/scCustomize#62]
- [x] #60 secondary y axis (add param or delay to 1.0.0 dev branch)
- [x] #54 finish CellBender additions (vignette)
- [x] #50 Finish Cell Complexity (vignette and plotting) 
- [x] #33 #16 Test functions continue replacements
- [x] #4 pull ensembl IDs using AnnotationHub and store in new function.
- [x] #47 Address issue
- [x] Dplyr import Add cell bender diff 
- [x] Check Liger to Seurat following matrix update
- [x] Check split level order (all modified split plot functions)
- [x] Push to master & update pkgdown site
- [x] any more???
